language: python

virtualenv:
    system_site_packages: true

python:
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

before_install:
    - sudo apt-get install -qq python-numpy python-scipy python-matplotlib python-gdal

install:
    - pip install .
