language: python

virtualenv:
    system_site_packages: true

python:
    - "2.6"
    - "2.7"
    - "3.2"
    - "3.3"
    - "pypy"

before_install:
    - sudo apt-get update -qq
    - sudo apt-get install -qq gdal-bin libproj-dev libgdal-dev
    - sudo apt-get install -qq python-numpy python-matplotlib python3-numpy python-gdal

install:
    - pip install .

script: nosetests

notifications:
  email:
    on_success: change
    on_failure: change
